apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.image.repository }}
  namespace: {{ .Values.namespaceName }}

spec:
  replicas: 1

  selector:
    matchLabels:
      app: {{ .Values.image.repository }}

  template:
    metadata:
      labels:
        app: {{ .Values.image.repository }}

    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "minorpatch/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbePath }}
              port: {{ .Values.containerPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbePath }}
              port: {{ .Values.containerPort }}
