apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.repository }}
  namespace: {{ .Values.namespaceName }}
  labels:
    app: {{ .Values.image.repository }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: {{ .Values.image.repository }}
  
  ports:
    - name: http
      port: {{ .Values.service.port }}
      {{ if .Values.service.targetPort }}
      targetPort: {{ .Values.service.targetPort }}
      {{ else }}
      targetPort: {{ .Values.service.port }}
      {{ end }}
      protocol: {{ .Values.service.protocol }}